### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by rapgro** [dnaeon/py-vconnector#10]
Just for your interest. There's now an official package available in Fedora, maintained by me.
We currently try to resolve a missing dependency in EPEL7 (additional repo for CentOS/RHEL 7), after a fix available there's going to be a package as well.

**Comment by rapgro** [comment]
OK
Please let me know if there's any need to have a package in all Fedora branches, like currently F28 and F29. For now, I decided to provide for Rawhide and EPEL7 because it's sufficient for my personal needs.

**Comment by dnaeon** [comment]
Just published `v0.7.3` on PyPI, which includes the LICENSE file as well.

I think it's sufficient only for EPEL7 for now, if there's any other need, perhaps people can package it as well.

Thanks!
Marin
