### ISSUE TITLE
Upgraded vCenter to version 7.0 and api hangs.

### ISSUE THREAD

**Issue by mechaHarry** [dnaeon/py-vconnector#12]
API was working fine on vCenters with 6.7 and under;
changed one to use 7.0 and now the programs built on this library hang during runtime.

**Comment by dnaeon** [comment]
Please provide some code samples to try out.

I haven't tested the library yet with 7.x

**Comment by dnaeon** [comment]
Just tested it against a vCenter 7.0.0 endpoint and things work as usual.

If you could provide a sample code that used to work and now it doesn't it would make it easier for me to test things out.

Here's a simple test I did.

```python
>>> agent.si.content.about.version
'7.0.0'
>>> vms_view = agent.get_vm_view()
>>> vms = agent.collect_properties(vms_view, pyVmomi.vim.VirtualMachine, ['name'])
>>> len(vms)
162
```
