### ISSUE TITLE
Not able to monitor power consumption 

### ISSUE THREAD

**Issue by JanLucasK** [dnaeon/py-vconnector#14]
Hello, I would be very grateful for help with my problem. 

I would like to query the energy consumption of my VMHosts, however I cannot find such a value/property. The closest I have come to are the values of various sensors via the Property Collector and 'runtime.healthSystemRuntime.systemHealthInfo.numericSensorInfo'. These values with the sensorType='power' added together make sense, but are not updated at the interval that power consumption is in vSphere. In vSphere the power consumption is shown every 20 seconds and the timestamps of the sensors (with this API) are hours old. Is there an easier way or is it even possible with this API? 

Also, I was wondering if there is a dictionary for the property names, because as far as I know they are different from PowerCLI and the propertys from vSphere Web Services API didn't work most of the time. So far I have had all the properties output and searched through the large file to find the individual properties.

Thanks in advance

**Comment by dnaeon** [comment]
Hey @JanLucasK , I'm not actively working on this project anymore, so I won't be able to test things out in a timely manner.

The property names come from the vSphere API documentation directly, not sure whether they are the same as in PowerCLI (not using it, so cannot tell).

Generally speaking any property name that you can pass to `pyVmomi` is accepted in `py-vconnector` as well.

The [vim.host.NumericSensorInfo.SensorType](https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere-ws/docs/ReferenceGuide/vim.host.NumericSensorInfo.SensorType.html) enum specifies another kind called `voltage`, but I cannot test that out now. Is this something that works for you?

**Comment by JanLucasK** [comment]
Thanks anyway for the answer, then I will inform myself otherwise. I will try the approach with the voltage.
